import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";

import "../globals.css";
import { SidebarDemo } from "./dashboard/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body>
          <Toaster />
          <ThemeProvider
            defaultTheme="dark"
            attribute="class"
            forcedTheme="dark"
          >
            <SidebarDemo>{children}</SidebarDemo>
          </ThemeProvider>
        </body>
      </ClerkProvider>
    </html>
  );
}
